### ISSUE TITLE
User Story: Job Server Integration

### ISSUE THREAD

**Issue by danielcsant** [Stratio/sparkta#374]
#### Tasks:
* [x] Check Sparkta's dependencies #384
* [ ] Ensure the Job Server's compatibility with Spark 1.4 and package it or contribute with project #385
* [x] Split Driver from REST API #392

#####  Driver refactor:
* [ ] Retrieve the policy from ZK #386
* [ ] Operational validation of the policy #387
* [x] Plugins selection and preparation of dependencies #388
* [x] Upload jars to JobServer #429
* [ ] Check dependencies already available in Job Server #389
* [ ] Policy submit #390

##### Job Server optional
* [x] Job Server API integrated into Sparkta API #440
* [x] Job Server's trait extension for standalone and Job Server #391
* [x] Job Server status #401

#####  Job Server's/Spark API integration
  * [x] Study both APIs
  * [x] Land as we implement this part

##### Job Server and Mesos
  * [ ] Study the support of Mesos and its versions
  * [ ] Impact
  * [ ] Evaluation test

**Comment by sgomezg** [comment]
We are not going to integrate JobServer for now
